// SPDX-License-Identifier: LicenseRef-PolyForm-Shield-1.0.0
// Copyright 2026 Vitaly Andrianov. See LICENSE.

// Managed agent backends: run the Claude Code CLI against an Anthropic-compatible endpoint
// (e.g. a Kimi subscription) without the user hand-writing a wrapper script. A backend is a
// human-readable JSON config (0600, holds the API key) plus a generated shell script (0700)
// that exports the environment and execs `claude`. The key lives ONLY in the 0600 JSON — never
// in the plugin's data.json, so it is not carried by Obsidian Sync or a vault backup.
//
// The `models` map mirrors opencode's provider shape (id -> { name, limit }), so the settings
// UI can show human-readable model names and context sizes.
import { promises as fs } from "fs";
import * as path from "path";

export interface BackendModel {
  name: string;
  contextTokens: number;
  outputTokens: number;
}

export interface BackendPreset {
  id: string;
  name: string;
  baseUrl: string;
  defaultModel: string;
  models: Record<string, BackendModel>;
}

// The on-disk backend config (backends/<id>.json). `authToken` is the secret.
export interface BackendConfig {
  name: string;
  baseUrl: string;
  authToken: string;
  model: string;
  models: Record<string, BackendModel>;
}

// v1 ships a single preset. Model ids and context sizes verified against `kimi acp` 0.24.2 and
// the Kimi Code docs; K3 released 2026-07-16.
export const BACKEND_PRESETS: Record<string, BackendPreset> = {
  kimi: {
    id: "kimi",
    name: "Kimi",
    baseUrl: "https://api.kimi.com/coding/",
    defaultModel: "k3[1m]",
    models: {
      "k3[1m]": { name: "Kimi K3 (1M context)", contextTokens: 1_000_000, outputTokens: 32_000 },
      k3: { name: "Kimi K3 (256K context)", contextTokens: 262_144, outputTokens: 32_000 },
      "kimi-for-coding": {
        name: "Kimi for Coding (K2.7)",
        contextTokens: 262_144,
        outputTokens: 32_000,
      },
    },
  },
};

// Seed a config from a preset, with an empty key for the user to fill in.
export function seedBackendConfig(preset: BackendPreset): BackendConfig {
  return {
    name: preset.name,
    baseUrl: preset.baseUrl,
    authToken: "",
    model: preset.defaultModel,
    models: preset.models,
  };
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

// The wrapper script generated from a backend config. Points the whole Claude Code session at
// the endpoint; every model tier maps to the chosen model so background/subagent calls do not
// ask the endpoint for a Claude model it does not serve.
export function generateBackendScript(config: BackendConfig): string {
  const lines = [
    "#!/bin/sh",
    "# Generated by Code Workbench from the backend JSON next to this file.",
    "# Edit the JSON in plugin settings, not this script — it is regenerated on every change.",
    "unset ANTHROPIC_API_KEY",
    `export ANTHROPIC_BASE_URL=${shQuote(config.baseUrl)}`,
    `export ANTHROPIC_AUTH_TOKEN=${shQuote(config.authToken)}`,
    `export ANTHROPIC_MODEL=${shQuote(config.model)}`,
    'export ANTHROPIC_DEFAULT_OPUS_MODEL="$ANTHROPIC_MODEL"',
    'export ANTHROPIC_DEFAULT_SONNET_MODEL="$ANTHROPIC_MODEL"',
    'export ANTHROPIC_DEFAULT_HAIKU_MODEL="$ANTHROPIC_MODEL"',
    'export CLAUDE_CODE_SUBAGENT_MODEL="$ANTHROPIC_MODEL"',
    "export ENABLE_TOOL_SEARCH=false",
  ];
  const model = config.models[config.model];
  if (model && model.contextTokens >= 1_000_000) {
    lines.push(`export CLAUDE_CODE_AUTO_COMPACT_WINDOW=${model.contextTokens}`);
    lines.push(`export CLAUDE_CODE_MAX_CONTEXT_TOKENS=${model.contextTokens}`);
  }
  lines.push('exec claude "$@"');
  return lines.join("\n") + "\n";
}

// Writes/reads the backend JSON (0600) and the generated script (0700) under
// `<pluginDir>/backends/`. Mirrors the companion token-store permission model.
export class AgentBackends {
  constructor(private readonly pluginDir: string) {}

  private dir(): string {
    return path.join(this.pluginDir, "backends");
  }

  configPath(id: string): string {
    return path.join(this.dir(), `${id}.json`);
  }

  scriptPath(id: string): string {
    return path.join(this.dir(), `${id}.sh`);
  }

  async readConfig(id: string): Promise<BackendConfig | null> {
    try {
      const raw = JSON.parse(await fs.readFile(this.configPath(id), "utf8")) as Partial<BackendConfig>;
      if (typeof raw.baseUrl !== "string" || typeof raw.model !== "string") return null;
      return {
        name: typeof raw.name === "string" ? raw.name : id,
        baseUrl: raw.baseUrl,
        authToken: typeof raw.authToken === "string" ? raw.authToken : "",
        model: raw.model,
        models: (raw.models as Record<string, BackendModel>) ?? {},
      };
    } catch {
      return null;
    }
  }

  // Persist the config (0600 JSON) and regenerate the script (0700). Returns the script path,
  // which is what a managed profile launches.
  async write(id: string, config: BackendConfig): Promise<string> {
    const dir = this.dir();
    await fs.mkdir(dir, { recursive: true });
    await fs.chmod(dir, 0o700).catch(() => undefined);

    const jsonTarget = this.configPath(id);
    const jsonTmp = `${jsonTarget}.tmp`;
    await fs.writeFile(jsonTmp, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });
    await fs.chmod(jsonTmp, 0o600).catch(() => undefined);
    await fs.rename(jsonTmp, jsonTarget);

    const script = this.scriptPath(id);
    await fs.writeFile(script, generateBackendScript(config), { mode: 0o700 });
    await fs.chmod(script, 0o700).catch(() => undefined);
    return script;
  }

  async remove(id: string): Promise<void> {
    await fs.unlink(this.configPath(id)).catch(() => undefined);
    await fs.unlink(this.scriptPath(id)).catch(() => undefined);
  }
}
